// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YC3.Data;

#nullable disable

namespace YC3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260114185821_SeedConcertAndSeats")]
    partial class SeedConcertAndSeats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YC3.Models.ConcertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            DateTime = new DateTime(2025, 12, 25, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đêm nhạc hoành tráng nhất năm",
                            Name = "The Eras Tour - Vietnam",
                            TotalSeats = 10
                        });
                });

            modelBuilder.Entity("YC3.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YC3.Models.Seat", b =>
                {
                    b.Property<Guid>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("RowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("SeatId");

                    b.HasIndex("EventId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = new Guid("ffafec5a-6c81-414f-b5b3-b998dd101174"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            RowName = "A",
                            SeatNumber = 1
                        },
                        new
                        {
                            SeatId = new Guid("6a44327f-97a0-4e71-aefc-55dfe4dabb23"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            RowName = "A",
                            SeatNumber = 2
                        },
                        new
                        {
                            SeatId = new Guid("a35ab57f-1d53-4018-a6a9-323a6002b11d"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            RowName = "A",
                            SeatNumber = 3
                        },
                        new
                        {
                            SeatId = new Guid("a970397c-3c8f-4e8e-a575-a24d3d0ecca5"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            RowName = "A",
                            SeatNumber = 4
                        },
                        new
                        {
                            SeatId = new Guid("31024cf6-6e7a-4e67-b2c8-be87cd821e20"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            RowName = "A",
                            SeatNumber = 5
                        },
                        new
                        {
                            SeatId = new Guid("9df7b1b1-40c1-4f5a-a310-0b884a7b576a"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            RowName = "B",
                            SeatNumber = 1
                        },
                        new
                        {
                            SeatId = new Guid("3a594d1b-3916-431c-a9c9-68fd2cbcd85d"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            RowName = "B",
                            SeatNumber = 2
                        },
                        new
                        {
                            SeatId = new Guid("734baade-366c-4810-a0d8-522ba1eaefbd"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            RowName = "B",
                            SeatNumber = 3
                        },
                        new
                        {
                            SeatId = new Guid("1b594fcf-06cf-4f15-a877-9e1a450ed44c"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            RowName = "B",
                            SeatNumber = 4
                        },
                        new
                        {
                            SeatId = new Guid("2babc1f4-b17f-4b3b-b3bf-7339b2e86432"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            RowName = "B",
                            SeatNumber = 5
                        });
                });

            modelBuilder.Entity("YC3.Models.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TicketId");

                    b.HasIndex("OrderId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("YC3.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YC3.Models.Order", b =>
                {
                    b.HasOne("YC3.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YC3.Models.Seat", b =>
                {
                    b.HasOne("YC3.Models.ConcertEvent", "Event")
                        .WithMany("Seats")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("YC3.Models.Ticket", b =>
                {
                    b.HasOne("YC3.Models.Order", null)
                        .WithMany("Tickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YC3.Models.ConcertEvent", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("YC3.Models.Order", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("YC3.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
