// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YC3.Data;

#nullable disable

namespace YC3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116094923_transient")]
    partial class transient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YC3.Models.ConcertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            DateTime = new DateTime(2025, 12, 25, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đêm nhạc hoành tráng nhất năm",
                            Name = "The Eras Tour - Vietnam",
                            TotalSeats = 10
                        });
                });

            modelBuilder.Entity("YC3.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YC3.Models.Seat", b =>
                {
                    b.Property<Guid>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConcertEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("SeatId");

                    b.HasIndex("ConcertEventId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = new Guid("a3d96d02-f3fb-4dca-8a4e-f6c9b12b70a6"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "A",
                            SeatNumber = 1
                        },
                        new
                        {
                            SeatId = new Guid("3f62c10f-d885-4110-be59-c84dc9f5d97a"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "A",
                            SeatNumber = 2
                        },
                        new
                        {
                            SeatId = new Guid("6929df17-19fe-406d-b778-a37d544c96b7"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "A",
                            SeatNumber = 3
                        },
                        new
                        {
                            SeatId = new Guid("d72af3ea-74c3-4223-90a5-d77cbadf7030"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "A",
                            SeatNumber = 4
                        },
                        new
                        {
                            SeatId = new Guid("752fca55-c87e-4a7a-9716-6f45621ddf75"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "A",
                            SeatNumber = 5
                        },
                        new
                        {
                            SeatId = new Guid("33cc6dc8-7836-48a1-aedf-0592650c11ed"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "B",
                            SeatNumber = 1
                        },
                        new
                        {
                            SeatId = new Guid("63f46c8b-daa9-486f-8ef9-6acfe7934437"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "B",
                            SeatNumber = 2
                        },
                        new
                        {
                            SeatId = new Guid("e0bae87f-6bd7-47bd-be27-2cdff548a816"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "B",
                            SeatNumber = 3
                        },
                        new
                        {
                            SeatId = new Guid("75f50dd4-71d4-4728-8a68-43b6f15b7db4"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "B",
                            SeatNumber = 4
                        },
                        new
                        {
                            SeatId = new Guid("ee65396b-fc73-45c0-8672-75e7a8ca7ead"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "B",
                            SeatNumber = 5
                        });
                });

            modelBuilder.Entity("YC3.Models.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceAtBooking")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TicketId");

                    b.HasIndex("OrderId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("YC3.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YC3.Models.Order", b =>
                {
                    b.HasOne("YC3.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YC3.Models.Seat", b =>
                {
                    b.HasOne("YC3.Models.ConcertEvent", null)
                        .WithMany("Seats")
                        .HasForeignKey("ConcertEventId");
                });

            modelBuilder.Entity("YC3.Models.Ticket", b =>
                {
                    b.HasOne("YC3.Models.Order", null)
                        .WithMany("Tickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YC3.Models.ConcertEvent", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("YC3.Models.Order", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("YC3.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
