// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YC3.Data;

#nullable disable

namespace YC3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120153102_AddPriceToSeatAndOrder")]
    partial class AddPriceToSeatAndOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YC3.Models.ConcertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            DateTime = new DateTime(2025, 12, 25, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đêm nhạc hoành tráng nhất năm",
                            Name = "The Eras Tour - Vietnam",
                            TotalSeats = 10
                        });
                });

            modelBuilder.Entity("YC3.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YC3.Models.Seat", b =>
                {
                    b.Property<Guid>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConcertEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("SeatId");

                    b.HasIndex("ConcertEventId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = new Guid("700e5b41-f4e8-4740-a47f-9baec6af89c7"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "A",
                            SeatNumber = 1
                        },
                        new
                        {
                            SeatId = new Guid("e237e2eb-5c58-4e4b-a595-b83f3cb4fb1b"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "A",
                            SeatNumber = 2
                        },
                        new
                        {
                            SeatId = new Guid("1c6303b3-6fa8-42a8-ab63-da97d9dfb7d3"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "A",
                            SeatNumber = 3
                        },
                        new
                        {
                            SeatId = new Guid("09fb82fe-f590-4264-9555-43e9a34d5bf6"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "A",
                            SeatNumber = 4
                        },
                        new
                        {
                            SeatId = new Guid("df587dc7-dd97-494e-ad91-5c51b41da1fb"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "A",
                            SeatNumber = 5
                        },
                        new
                        {
                            SeatId = new Guid("f1d7898a-02eb-4809-8ffc-7b6b19dfdb2a"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "B",
                            SeatNumber = 1
                        },
                        new
                        {
                            SeatId = new Guid("4ed4a8f1-d2c8-4cc3-b774-55ce5dce17d4"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "B",
                            SeatNumber = 2
                        },
                        new
                        {
                            SeatId = new Guid("bbb1d45f-ab2e-45b8-ad30-fc3b039b8f1f"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "B",
                            SeatNumber = 3
                        },
                        new
                        {
                            SeatId = new Guid("19144aad-8cd3-4ce8-a471-a27dd3995c01"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "B",
                            SeatNumber = 4
                        },
                        new
                        {
                            SeatId = new Guid("5299d0bb-5ff4-42ad-ad1c-9a1017985c31"),
                            EventId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsAvailable = true,
                            Price = 0m,
                            RowName = "B",
                            SeatNumber = 5
                        });
                });

            modelBuilder.Entity("YC3.Models.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceAtBooking")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TicketId");

                    b.HasIndex("OrderId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("YC3.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YC3.Models.Order", b =>
                {
                    b.HasOne("YC3.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YC3.Models.Seat", b =>
                {
                    b.HasOne("YC3.Models.ConcertEvent", null)
                        .WithMany("Seats")
                        .HasForeignKey("ConcertEventId");
                });

            modelBuilder.Entity("YC3.Models.Ticket", b =>
                {
                    b.HasOne("YC3.Models.Order", null)
                        .WithMany("Tickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YC3.Models.ConcertEvent", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("YC3.Models.Order", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("YC3.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
